/*
 * @class Type:  View Class
 * @description: This class aims to construct the JPanel which can decide 
 *               whether shading elapsed time information panel
 */

package numbersliderpuzzlegame.view;

import java.awt.Color;
import java.awt.Graphics;

/**
 * project: A desktop based number sliding puzzle game application
 * email:   chenc5@andrew.cmu.edu
 * @author  Chen Chen
 * Created in 2016, at the University of Nottingham, UK  
 */

public class TimeElapsedShaderPanel extends javax.swing.JPanel {

    /**
     * Constructor
     * <p> Creates new form TimeElapsedShaderPanel
     */
    public TimeElapsedShaderPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Paint elapsed time shader if needed
     * 
     * @param g Graphics
     */
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        // shade elapsed time counter using a black blcok
        if(NumberSliderPuzzleGameMainFrame.isShadeElapseTimer){
            g.setColor(Color.black);
            g.fillRect(shaderPositionX, 
                       shaderPositionY, 
                       shaderPositionWidth, 
                       shaderPositionHeight);
        } // end if
        
        // remove the black block
        if(!NumberSliderPuzzleGameMainFrame.isShadeElapseTimer){  
            g.setColor(this.getBackground());
            g.fillRect(shaderPositionX, 
                       shaderPositionY, 
                       shaderPositionWidth, 
                       shaderPositionHeight);
        } // end if
    } // end method

    // defind the dimensions of shader block
    // improvements may be required if the dimension needs be changed
    private static final int shaderPositionX = 31;
    private static final int shaderPositionY = 0;
    private static final int shaderPositionWidth = 100;
    private static final int shaderPositionHeight = 20;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
